require 'singleton'
require 'symbolmatrix'
require 'discoverer'
require 'term/ansicolor'
require 'logger'
require 'fast/fast'

require 'empezar/version'
require 'empezar/exceptions'
require 'empezar/configuration'
require 'empezar/runner'
require 'empezar/echoing_formatter'
require 'empezar/log'
require 'empezar/scaffold'